#!/bin/bash
PWD=`pwd`
SETUPT_PATH="../library/openssl"

cd ./openssl-1.0.2o/

if [ ! -e ${SETUPT_PATH} ]; then
	mkdir -p ${SETUPT_PATH}
else
	rm -rf ${SETUPT_PATH}/*
fi

#./Configure linux-x86_64 no-md2 no-mdc2 no-rc5 no-rc4 -DOPENSSL_THREADS -D_REENTRANT --prefix=${PWD}/${SETUPT_PATH}

./Configure linux-x86_64 no-shared --prefix=${PWD}/${SETUPT_PATH} -DOPENSSL_THREADS -D_REENTRANT -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM  -DECP_NISTZ256_ASM  -DOPENSSL_NO_EC_NISTP_64_GCC_128 -DOPENSSL_NO_GMP -DOPENSSL_NO_JPAKE -DOPENSSL_NO_LIBUNBOUND -DOPENSSL_NO_MD2 -DOPENSSL_NO_RC5 -DOPENSSL_NO_RFC3779 -DOPENSSL_NO_SCTP -DOPENSSL_NO_SSL_TRACE -DOPENSSL_NO_STORE -DOPENSSL_NO_UNIT_TEST

make depend && make -j 11
make install
